"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireModule } from "@/lib/auth";
function positive(v:unknown){const n=Number(v);if(!Number.isFinite(n)||n<=0)throw new Error("Jumlah/nominal tidak valid.");return n;}
function selectedCategory(fd:FormData){const category=String(fd.get("category")||"").trim();if(category!=="Lainnya")return category||"Lainnya";return String(fd.get("category_other")||"").trim()||"Lainnya";}
function refresh(){revalidatePath("/shopping");revalidatePath("/finance");revalidatePath("/dashboard");revalidatePath("/reports");}
export async function addShoppingEntry(fd:FormData){const {supabase,userId}=await requireModule("shopping");let receiptPath:string|null=null;const receipt=fd.get("receipt");if(receipt instanceof File&&receipt.size>0){if(receipt.size>8*1024*1024)throw new Error("Ukuran struk maksimal 8 MB.");const safe=receipt.name.replace(/[^a-zA-Z0-9._-]/g,"-");receiptPath=`${userId}/${crypto.randomUUID()}-${safe}`;const {error:upErr}=await supabase.storage.from("receipts").upload(receiptPath,receipt,{upsert:false});if(upErr)throw new Error(upErr.message)}const id=crypto.randomUUID();const itemName=String(fd.get("item_name")||"").trim();const category=selectedCategory(fd);const quantity=positive(fd.get("quantity")||1);const unit=String(fd.get("unit")||"pcs").trim();const totalAmount=positive(fd.get("total_amount"));const storeName=String(fd.get("store_name")||"").trim();const notes=String(fd.get("notes")||"").trim();const purchasedAt=String(fd.get("purchased_at"));const {error}=await supabase.from("shopping_entries").insert({id,user_id:userId,item_name:itemName,category,quantity,unit,total_amount:totalAmount,store_name:storeName,notes,purchased_at:purchasedAt,receipt_path:receiptPath});if(error){if(receiptPath)await supabase.storage.from("receipts").remove([receiptPath]);throw new Error(error.message)}const {error:financeError}=await supabase.from("finance_transactions").insert({id,user_id:userId,kind:"expense",amount:totalAmount,category,description:itemName,payment_method:"Belanja otomatis",transaction_date:purchasedAt});if(financeError){await supabase.from("shopping_entries").delete().eq("id",id).eq("user_id",userId);if(receiptPath)await supabase.storage.from("receipts").remove([receiptPath]);throw new Error(`Belanja gagal disinkronkan ke Keuangan: ${financeError.message}`)}refresh();redirect("/shopping?success=entry");}
export async function deleteShoppingEntry(fd:FormData){const {supabase,userId}=await requireModule("shopping");const id=String(fd.get("id"));const {data:row}=await supabase.from("shopping_entries").select("receipt_path").eq("id",id).eq("user_id",userId).maybeSingle();const {error}=await supabase.from("shopping_entries").delete().eq("id",id).eq("user_id",userId);if(error)throw new Error(error.message);await supabase.from("finance_transactions").delete().eq("id",id).eq("user_id",userId).eq("payment_method","Belanja otomatis");if(row?.receipt_path)await supabase.storage.from("receipts").remove([row.receipt_path]);refresh();}
export async function addWishlistItem(fd:FormData){const {supabase,userId}=await requireModule("shopping");const {error}=await supabase.from("shopping_wishlist").insert({user_id:userId,item_name:String(fd.get("item_name")||"").trim(),category:selectedCategory(fd),estimated_amount:Number(fd.get("estimated_amount")||0),priority:String(fd.get("priority")||"normal"),notes:String(fd.get("notes")||"").trim()});if(error)throw new Error(error.message);refresh();redirect("/shopping?success=wishlist");}
export async function toggleWishlist(fd:FormData){const {supabase,userId}=await requireModule("shopping");const done=String(fd.get("done"))==="true";const {error}=await supabase.from("shopping_wishlist").update({is_done:!done}).eq("id",String(fd.get("id"))).eq("user_id",userId);if(error)throw new Error(error.message);refresh();}
