"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireModule } from "@/lib/auth";
function positive(v:unknown){const n=Number(v);if(!Number.isFinite(n)||n<=0)throw new Error("Jumlah/nominal tidak valid.");return n;}
function refresh(){revalidatePath("/shopping");revalidatePath("/dashboard");revalidatePath("/reports");}
export async function addShoppingEntry(fd:FormData){const {supabase,userId}=await requireModule("shopping");let receiptPath:string|null=null;const receipt=fd.get("receipt");if(receipt instanceof File&&receipt.size>0){if(receipt.size>8*1024*1024)throw new Error("Ukuran struk maksimal 8 MB.");const safe=receipt.name.replace(/[^a-zA-Z0-9._-]/g,"-");receiptPath=`${userId}/${crypto.randomUUID()}-${safe}`;const {error:upErr}=await supabase.storage.from("receipts").upload(receiptPath,receipt,{upsert:false});if(upErr)throw new Error(upErr.message)}const {error}=await supabase.from("shopping_entries").insert({user_id:userId,item_name:String(fd.get("item_name")||"").trim(),category:String(fd.get("category")||"Lainnya").trim(),quantity:positive(fd.get("quantity")||1),unit:String(fd.get("unit")||"pcs").trim(),total_amount:positive(fd.get("total_amount")),store_name:String(fd.get("store_name")||"").trim(),notes:String(fd.get("notes")||"").trim(),purchased_at:String(fd.get("purchased_at")),receipt_path:receiptPath});if(error){if(receiptPath)await supabase.storage.from("receipts").remove([receiptPath]);throw new Error(error.message)}refresh();redirect("/shopping?success=entry");}
export async function deleteShoppingEntry(fd:FormData){const {supabase,userId}=await requireModule("shopping");const id=String(fd.get("id"));const {data:row}=await supabase.from("shopping_entries").select("receipt_path").eq("id",id).eq("user_id",userId).maybeSingle();const {error}=await supabase.from("shopping_entries").delete().eq("id",id).eq("user_id",userId);if(error)throw new Error(error.message);if(row?.receipt_path)await supabase.storage.from("receipts").remove([row.receipt_path]);refresh();}
export async function addWishlistItem(fd:FormData){const {supabase,userId}=await requireModule("shopping");const {error}=await supabase.from("shopping_wishlist").insert({user_id:userId,item_name:String(fd.get("item_name")||"").trim(),category:String(fd.get("category")||"Lainnya").trim(),estimated_amount:Number(fd.get("estimated_amount")||0),priority:String(fd.get("priority")||"normal"),notes:String(fd.get("notes")||"").trim()});if(error)throw new Error(error.message);refresh();redirect("/shopping?success=wishlist");}
export async function toggleWishlist(fd:FormData){const {supabase,userId}=await requireModule("shopping");const done=String(fd.get("done"))==="true";const {error}=await supabase.from("shopping_wishlist").update({is_done:!done}).eq("id",String(fd.get("id"))).eq("user_id",userId);if(error)throw new Error(error.message);refresh();}
