import Link from "next/link";
import { AlertTriangle, Boxes, Factory, PackageSearch, ReceiptText } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { ModuleSubnav } from "@/components/module-subnav";
import { SectionCard } from "@/components/section-card";
import { StatCard } from "@/components/stat-card";
import { EmptyState } from "@/components/empty-state";
import { requireModule } from "@/lib/auth";
import { readableDate, rupiah, today } from "@/lib/format";
import { kebabNav } from "@/features/kebab/nav";

export default async function KebabOverview(){const {supabase}=await requireModule("kebab");const [ingredientsRes,recipesRes,prodRes,purchaseRes,wasteRes]=await Promise.all([supabase.from("kebab_ingredients").select("id,name,unit,stock_quantity,low_stock_threshold,expires_at,last_unit_cost").order("name"),supabase.from("kebab_recipes").select("id,name,active").eq("active",true),supabase.from("kebab_productions").select("id,quantity,production_date,kebab_recipes(name)").order("production_date",{ascending:false}).limit(20),supabase.from("kebab_purchases").select("id,total_cost,purchased_at").order("purchased_at",{ascending:false}).limit(50),supabase.from("kebab_waste").select("id,quantity,waste_date,kebab_ingredients(name,unit)").order("waste_date",{ascending:false}).limit(10)]);const ingredients=ingredientsRes.data??[];const recipes=recipesRes.data??[];const productions=prodRes.data??[];const low=ingredients.filter((x:any)=>Number(x.stock_quantity)<=Number(x.low_stock_threshold));const todayProduction=productions.filter((x:any)=>x.production_date===today()).reduce((s:number,x:any)=>s+Number(x.quantity),0);const month=today().slice(0,7);const monthPurchase=(purchaseRes.data??[]).filter((x:any)=>String(x.purchased_at).startsWith(month)).reduce((s:number,x:any)=>s+Number(x.total_cost),0);const expirySoon=ingredients.filter((x:any)=>{if(!x.expires_at)return false;const d=new Date(`${x.expires_at}T23:59:59`);return d<=new Date(Date.now()+7*86400000)});
return <><PageHeader eyebrow="Modul khusus Finka" title="Operasional Finka" description="Pengelolaan bahan, supplier, pembelian, resep, produksi harian, waste, stok opname, dan peringatan stok. Modul ini tidak muncul pada akun tanpa akses kebab."/><ModuleSubnav items={kebabNav}/><div className="grid gap-4 md:grid-cols-4"><StatCard label="Jenis bahan" value={String(ingredients.length)} icon={Boxes}/><StatCard label="Stok menipis" value={String(low.length)} icon={AlertTriangle}/><StatCard label="Produksi hari ini" value={`${todayProduction} pcs`} icon={Factory}/><StatCard label="Belanja bahan bulan ini" value={rupiah(monthPurchase)} icon={ReceiptText}/></div>
{(low.length>0||expirySoon.length>0)&&<SectionCard title="Peringatan stok & kedaluwarsa"><div className="grid gap-3 md:grid-cols-2">{low.map((x:any)=><div key={`low-${x.id}`} className="rounded-xl bg-red-50 p-4"><p className="font-black text-red-800">{x.name} hampir habis</p><p className="mt-1 text-sm text-red-700">Sisa {x.stock_quantity} {x.unit} · batas minimum {x.low_stock_threshold} {x.unit}</p></div>)}{expirySoon.map((x:any)=><div key={`exp-${x.id}`} className="rounded-xl bg-amber-50 p-4"><p className="font-black text-amber-800">{x.name} mendekati expired</p><p className="mt-1 text-sm text-amber-700">Tanggal {readableDate(x.expires_at)}</p></div>)}</div></SectionCard>}
<SectionCard title="Akses cepat"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Quick href="/kebab/ingredients" title="Bahan & Stok"/><Quick href="/kebab/recipes" title="Resep"/><Quick href="/kebab/production" title="Produksi"/><Quick href="/kebab/purchases" title="Pembelian"/><Quick href="/kebab/stock" title="Waste & Opname"/></div></SectionCard>
<div className="grid gap-6 xl:grid-cols-2"><SectionCard title="Produksi terbaru">{productions.length===0?<EmptyState/>:<div className="space-y-2">{productions.map((p:any)=><div key={p.id} className="flex items-center justify-between rounded-xl bg-neutral-50 p-3"><div><p className="font-bold">{p.kebab_recipes?.name||"Produksi"}</p><p className="text-xs text-neutral-500">{readableDate(p.production_date)}</p></div><b>{p.quantity} pcs</b></div>)}</div>}</SectionCard><SectionCard title="Waste terbaru">{(wasteRes.data??[]).length===0?<EmptyState/>:<div className="space-y-2">{(wasteRes.data??[]).map((w:any)=><div key={w.id} className="flex justify-between rounded-xl bg-neutral-50 p-3"><div><p className="font-bold">{w.kebab_ingredients?.name||"Bahan"}</p><p className="text-xs text-neutral-500">{readableDate(w.waste_date)}</p></div><b className="text-red-600">-{w.quantity} {w.kebab_ingredients?.unit}</b></div>)}</div>}</SectionCard></div></>}
function Quick({href,title}:{href:string;title:string}){return <Link href={href} className="rounded-xl border border-black/5 bg-neutral-50 p-4 transition hover:bg-orange-50"><PackageSearch size={18} className="text-orange-600"/><p className="mt-3 font-black">{title}</p><p className="mt-1 text-xs font-bold text-orange-600">Buka →</p></Link>}
