import { notFound } from "next/navigation";
import { PageHeader } from "@/components/page-header";
import { SectionCard } from "@/components/section-card";
import { SubmitButton } from "@/components/submit-button";
import { ProgressBar } from "@/components/progress-bar";
import { requireModule } from "@/lib/auth";
import { readableDate } from "@/lib/format";
import { addAssignmentStep, setAssignmentProgress, toggleAssignmentStep } from "@/features/academic/actions";

export default async function AssignmentWorkspace({params}:{params:Promise<{id:string}>}){const {id}=await params;const {supabase}=await requireModule("academic");const [{data:a},{data:steps}]=await Promise.all([supabase.from("academic_assignments").select("id,title,description,due_date,priority,progress,is_done,academic_courses(name)").eq("id",id).maybeSingle(),supabase.from("academic_assignment_steps").select("id,title,is_done,position").eq("assignment_id",id).order("position").order("created_at")]);if(!a)notFound();const list=steps??[];const done=list.filter((x:any)=>x.is_done).length;return <><PageHeader eyebrow="Assignment Workspace" title={a.title} description={`${a.academic_courses?.name||"Umum"} · deadline ${readableDate(a.due_date)} · prioritas ${a.priority}`}/><SectionCard title="Progress tugas"><ProgressBar value={Number(a.progress)} label={`${Number(a.progress)}%`}/><form action={setAssignmentProgress} className="mt-4 flex max-w-sm gap-2"><input type="hidden" name="id" value={a.id}/><input className="field" name="progress" type="number" min="0" max="100" defaultValue={a.progress}/><SubmitButton>Update</SubmitButton></form>{a.description&&<p className="mt-4 whitespace-pre-wrap rounded-xl bg-neutral-50 p-4 text-sm leading-6 text-neutral-600">{a.description}</p>}</SectionCard><SectionCard title="Checklist pengerjaan" description={`${done}/${list.length} langkah selesai`}><form action={addAssignmentStep} className="mb-4 flex gap-2"><input type="hidden" name="assignment_id" value={a.id}/><input type="hidden" name="position" value={list.length}/><input className="field" name="title" placeholder="Contoh: Buat ERD" required/><SubmitButton>Tambah</SubmitButton></form><div className="space-y-2">{list.map((s:any)=><form action={toggleAssignmentStep} key={s.id} className={`flex items-center justify-between rounded-xl p-3 ${s.is_done?"bg-emerald-50":"bg-neutral-50"}`}><input type="hidden" name="id" value={s.id}/><input type="hidden" name="assignment_id" value={a.id}/><input type="hidden" name="done" value={String(s.is_done)}/><span className={`text-sm font-bold ${s.is_done?"line-through opacity-60":""}`}>{s.title}</span><button className="btn-soft">{s.is_done?"Batal":"Selesai"}</button></form>)}</div></SectionCard></>}
