import { CheckCircle2, ShoppingBag, WalletCards } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { SectionCard } from "@/components/section-card";
import { StatCard } from "@/components/stat-card";
import { SubmitButton } from "@/components/submit-button";
import { EmptyState } from "@/components/empty-state";
import { requireModule } from "@/lib/auth";
import { monthRange, readableDate, rupiah, today } from "@/lib/format";
import { addShoppingEntry, addWishlistItem, deleteShoppingEntry, toggleWishlist } from "@/features/shopping/actions";

export default async function ShoppingPage({searchParams}:{searchParams:Promise<{success?:string}>}){
 const {supabase}=await requireModule("shopping");const {start,end}=monthRange();
 const [entryRes,monthEntryRes,wishRes]=await Promise.all([supabase.from("shopping_entries").select("id,item_name,category,quantity,unit,total_amount,store_name,notes,purchased_at,receipt_path").order("purchased_at",{ascending:false}).order("created_at",{ascending:false}).limit(150),supabase.from("shopping_entries").select("id,total_amount").gte("purchased_at",start).lt("purchased_at",end),supabase.from("shopping_wishlist").select("id,item_name,category,estimated_amount,priority,notes,is_done,created_at").order("is_done").order("created_at",{ascending:false})]);
 const entries=entryRes.data??[];const monthEntries=monthEntryRes.data??[];const total=monthEntries.reduce((s:number,x:any)=>s+Number(x.total_amount),0);const wishlist=wishRes.data??[];const entriesWithReceipts=await Promise.all(entries.map(async (x:any)=>{if(!x.receipt_path)return {...x,receipt_url:null};const {data}=await supabase.storage.from("receipts").createSignedUrl(x.receipt_path,3600);return {...x,receipt_url:data?.signedUrl??null};}));const params=await searchParams;
 return <><PageHeader eyebrow="Modul umum · data pribadi" title="Belanja" description="Catat apa saja yang dibeli setiap bulan. Data Rahmat dan Finka tetap terpisah meski fiturnya sama."/>{params.success&&<div className="rounded-xl bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-700">Data belanja berhasil disimpan.</div>}
 <div className="grid gap-4 md:grid-cols-3"><StatCard label="Belanja bulan ini" value={rupiah(total)} icon={WalletCards}/><StatCard label="Item tercatat" value={String(monthEntries.length)} icon={ShoppingBag}/><StatCard label="Wishlist aktif" value={String(wishlist.filter((x:any)=>!x.is_done).length)} icon={CheckCircle2}/></div>
 <div className="grid gap-6 xl:grid-cols-2"><SectionCard title="Catat belanja"><form action={addShoppingEntry} className="grid gap-3 sm:grid-cols-2"><input className="field sm:col-span-2" name="item_name" placeholder="Nama barang" required/><input className="field" name="category" placeholder="Kategori" required/><input className="field" name="store_name" placeholder="Toko/tempat beli"/><input className="field" name="quantity" type="number" step="0.01" min="0.01" defaultValue="1" required/><input className="field" name="unit" defaultValue="pcs" placeholder="Satuan"/><input className="field" name="total_amount" type="number" min="1" placeholder="Total harga" required/><input className="field" name="purchased_at" type="date" defaultValue={today()} required/><textarea className="field min-h-20 sm:col-span-2" name="notes" placeholder="Catatan opsional"/><div className="sm:col-span-2"><label className="label">Foto/PDF struk (opsional)</label><input className="field" name="receipt" type="file" accept="image/*,application/pdf"/></div><SubmitButton>Tambah belanja</SubmitButton></form></SectionCard>
 <SectionCard title="Wishlist belanja" description="Barang yang ingin dibeli sebelum menjadi transaksi."><form action={addWishlistItem} className="grid gap-3 sm:grid-cols-2"><input className="field sm:col-span-2" name="item_name" placeholder="Barang yang diinginkan" required/><input className="field" name="category" placeholder="Kategori" required/><input className="field" name="estimated_amount" type="number" min="0" placeholder="Estimasi harga"/><select className="field" name="priority"><option value="low">Rendah</option><option value="normal">Normal</option><option value="high">Tinggi</option></select><input className="field" name="notes" placeholder="Catatan"/><SubmitButton>Tambah wishlist</SubmitButton></form><div className="mt-4 space-y-2">{wishlist.length===0?<EmptyState/>:wishlist.map((w:any)=><div key={w.id} className={`rounded-xl p-3 ${w.is_done?"bg-neutral-50 opacity-60":"bg-orange-50"}`}><div className="flex items-center justify-between gap-3"><div><p className={`font-bold ${w.is_done?"line-through":""}`}>{w.item_name}</p><p className="text-xs text-neutral-500">{w.category} · estimasi {rupiah(w.estimated_amount)}</p></div><form action={toggleWishlist}><input type="hidden" name="id" value={w.id}/><input type="hidden" name="done" value={String(w.is_done)}/><button className="btn-soft">{w.is_done?"Aktifkan":"Selesai"}</button></form></div></div>)}</div></SectionCard></div>
 <SectionCard title="Riwayat belanja" description="150 catatan terbaru.">{entriesWithReceipts.length===0?<EmptyState/>:<div className="table-wrap"><table className="table"><thead><tr><th>Tanggal</th><th>Barang</th><th>Kategori</th><th>Jumlah</th><th>Toko</th><th>Total</th><th>Struk</th><th></th></tr></thead><tbody>{entriesWithReceipts.map((x:any)=><tr key={x.id}><td>{readableDate(x.purchased_at)}</td><td><b>{x.item_name}</b>{x.notes&&<div className="text-xs text-neutral-400">{x.notes}</div>}</td><td>{x.category}</td><td>{x.quantity} {x.unit}</td><td>{x.store_name||"-"}</td><td className="font-black">{rupiah(x.total_amount)}</td><td>{x.receipt_url?<a className="text-xs font-bold text-orange-600" href={x.receipt_url} target="_blank" rel="noreferrer">Buka</a>:"-"}</td><td><form action={deleteShoppingEntry}><input type="hidden" name="id" value={x.id}/><button className="btn-danger">Hapus</button></form></td></tr>)}</tbody></table></div>}</SectionCard></>;
}
