import { FileText, Link2, NotebookText } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { ModuleSubnav } from "@/components/module-subnav";
import { SectionCard } from "@/components/section-card";
import { SubmitButton } from "@/components/submit-button";
import { EmptyState } from "@/components/empty-state";
import { requireModule } from "@/lib/auth";
import { readableDateTime } from "@/lib/format";
import { academicNav } from "@/features/academic/nav";
import { addNote, deleteMaterial, uploadMaterial } from "@/features/academic/actions";

const ASSIGNMENT_PROGRESS_PREFIX = "ourjournal:assignment-progress:";

export default async function MaterialsPage({searchParams}:{searchParams:Promise<{success?:string}>}){const {supabase}=await requireModule("academic");const [coursesRes,notesRes,materialsRes]=await Promise.all([supabase.from("academic_courses").select("id,name").order("name"),supabase.from("academic_notes").select("id,title,content,meeting_no,resource_url,created_at,academic_courses(name)").not("resource_url","like",`${ASSIGNMENT_PROGRESS_PREFIX}%`).order("created_at",{ascending:false}).limit(80),supabase.from("academic_materials").select("id,title,file_name,file_size,mime_type,storage_path,created_at,academic_courses(name)").order("created_at",{ascending:false}).limit(80)]);const courses=coursesRes.data??[];const notes=notesRes.data??[];const materials=materialsRes.data??[];
const materialLinks=await Promise.all(materials.map(async (m:any)=>{const {data}=await supabase.storage.from("academic-materials").createSignedUrl(m.storage_path,3600);return {...m,signed_url:data?.signedUrl??null};}));const params=await searchParams;
return <><PageHeader eyebrow="Kuliah" title="Catatan & Materi" description="Simpan catatan per pertemuan, link referensi, PDF, PPT, dan file kuliah. File masuk ke Supabase Storage privat."/><ModuleSubnav items={academicNav}/>{params.success&&<div className="rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-700">Berhasil disimpan.</div>}
<div className="grid gap-6 xl:grid-cols-2"><SectionCard title="Catatan kuliah"><form action={addNote} className="space-y-3"><select className="field" name="course_id"><option value="">Umum</option>{courses.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input className="field" name="title" placeholder="Judul catatan" required/><input className="field" name="meeting_no" type="number" min="0" placeholder="Pertemuan ke-"/><textarea className="field min-h-32" name="content" placeholder="Isi catatan"/><input className="field" name="resource_url" type="url" placeholder="Link referensi opsional"/><SubmitButton>Simpan catatan</SubmitButton></form></SectionCard><SectionCard title="Upload materi" description="Maksimal 10 MB per file pada kode saat ini."><form action={uploadMaterial} className="space-y-3"><select className="field" name="course_id"><option value="">Umum</option>{courses.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input className="field" name="title" placeholder="Judul materi"/><input className="field" name="file" type="file" required/><SubmitButton>Upload file</SubmitButton></form></SectionCard></div>
<div className="grid gap-6 xl:grid-cols-2"><SectionCard title="Catatan terbaru">{notes.length===0?<EmptyState/>:<div className="space-y-3">{notes.map((n:any)=><article key={n.id} className="rounded-xl border border-black/5 p-4"><div className="flex gap-3"><NotebookText className="mt-0.5 text-orange-600" size={18}/><div><p className="font-black">{n.title}</p><p className="text-xs text-neutral-500">{n.academic_courses?.name||"Umum"}{n.meeting_no?` · Pertemuan ${n.meeting_no}`:""} · {readableDateTime(n.created_at)}</p></div></div><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-neutral-600">{n.content||"Tidak ada isi."}</p>{n.resource_url&&<a href={n.resource_url} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-orange-600"><Link2 size={13}/> Referensi</a>}</article>)}</div>}</SectionCard><SectionCard title="File materi">{materialLinks.length===0?<EmptyState/>:<div className="space-y-2">{materialLinks.map((m:any)=><div key={m.id} className="flex items-center gap-3 rounded-xl bg-neutral-50 p-3"><div className="rounded-lg bg-white p-2 text-orange-600"><FileText size={18}/></div><div className="min-w-0 flex-1"><p className="truncate font-bold">{m.title||m.file_name}</p><p className="text-xs text-neutral-500">{m.academic_courses?.name||"Umum"} · {(Number(m.file_size)/1024).toFixed(0)} KB</p><p className="truncate text-[11px] text-neutral-400">{m.file_name}</p></div><div className="flex shrink-0 gap-2">{m.signed_url&&<a className="btn-soft" href={m.signed_url} target="_blank" rel="noreferrer">Buka</a>}<form action={deleteMaterial}><input type="hidden" name="id" value={m.id}/><button className="btn-danger">Hapus</button></form></div></div>)}</div>}<p className="mt-4 text-xs leading-5 text-neutral-400">File tetap privat; tombol Buka memakai signed URL sementara selama 1 jam.</p></SectionCard></div></>}
