import { Brain, CalendarClock } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { ModuleSubnav } from "@/components/module-subnav";
import { SectionCard } from "@/components/section-card";
import { EmptyState } from "@/components/empty-state";
import { academicNav } from "@/features/academic/nav";
import { requireModule } from "@/lib/auth";
import { readableDate, today } from "@/lib/format";

export default async function StudyPlannerPage(){const {supabase}=await requireModule("academic");const {data}=await supabase.from("academic_assignments").select("id,title,due_date,priority,progress,academic_courses(name)").eq("is_done",false).gte("due_date",today()).order("due_date").limit(30);const tasks=(data??[]).map((a:any)=>{const days=Math.max(0,Math.ceil((new Date(`${a.due_date}T23:59:59`).getTime()-Date.now())/86400000));const urgency=Math.max(1,8-Math.min(days,7));const priority=a.priority==="high"?3:a.priority==="low"?1:2;const remaining=Math.max(0,100-Number(a.progress||0));const score=urgency*priority*(remaining/100);return {...a,days,score}}).sort((a:any,b:any)=>b.score-a.score);const days=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()+i);return d});const plan=days.map((d,i)=>({date:d,tasks:tasks.filter((_:any,index:number)=>index%7===i).slice(0,3)}));return <><PageHeader eyebrow="Kuliah" title="Study Planner" description="Planner otomatis berbasis deadline, prioritas, dan progress tugas. Tidak membutuhkan API AI, sehingga tetap gratis dan bisa menjadi dasar AI Study Assistant nanti."/><ModuleSubnav items={academicNav}/><SectionCard title="Prioritas saat ini" description="Skor lebih tinggi berarti lebih mendesak untuk dikerjakan.">{tasks.length===0?<EmptyState>Tidak ada tugas aktif yang perlu direncanakan.</EmptyState>:<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{tasks.slice(0,6).map((t:any)=><div key={t.id} className="rounded-xl border border-black/5 p-4"><div className="flex items-start justify-between"><Brain size={18} className="text-orange-600"/><span className="pill">{t.days} hari lagi</span></div><p className="mt-3 font-black">{t.title}</p><p className="mt-1 text-xs text-neutral-500">{t.academic_courses?.name||"Umum"} · progress {t.progress}%</p><p className="mt-3 text-xs font-bold text-orange-600">Skor prioritas {t.score.toFixed(1)}</p></div>)}</div>}</SectionCard><SectionCard title="Rencana 7 hari" description="Distribusi sederhana. Nanti bisa ditingkatkan memakai jadwal kosong dan model AI."><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{plan.map((p:any)=><div key={p.date.toISOString()} className="rounded-xl bg-neutral-50 p-4"><div className="flex items-center gap-2"><CalendarClock size={16} className="text-orange-600"/><p className="font-black">{readableDate(p.date)}</p></div><div className="mt-3 space-y-2">{p.tasks.length===0?<p className="text-xs text-neutral-400">Review ringan / istirahat.</p>:p.tasks.map((t:any)=><div key={t.id} className="rounded-lg bg-white p-2 text-xs"><b>{t.title}</b><p className="mt-1 text-neutral-500">Saran: 25–50 menit</p></div>)}</div></div>)}</div></SectionCard></>}
