"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireModule } from "@/lib/auth";

function positive(v: FormDataEntryValue | null) { const n=Number(v); if(!Number.isFinite(n)||n<=0) throw new Error("Nominal harus lebih dari 0."); return n; }
function selectedCategory(fd:FormData){const category=String(fd.get("category")||"").trim();if(category!=="Lainnya")return category||"Lainnya";return String(fd.get("category_other")||"").trim()||"Lainnya";}
function refresh(){ revalidatePath("/finance"); revalidatePath("/shopping"); revalidatePath("/dashboard"); revalidatePath("/reports"); }

export async function addTransaction(fd:FormData){ const {supabase,userId}=await requireModule("finance"); const kind=String(fd.get("kind")); if(!["income","expense"].includes(kind)) throw new Error("Jenis transaksi tidak valid."); const {error}=await supabase.from("finance_transactions").insert({user_id:userId,kind,amount:positive(fd.get("amount")),category:selectedCategory(fd),description:String(fd.get("description")||"").trim(),payment_method:String(fd.get("payment_method")||"Tunai").trim(),transaction_date:String(fd.get("transaction_date"))}); if(error) throw new Error(error.message); refresh(); redirect("/finance?success=transaction"); }
export async function deleteTransaction(fd:FormData){ const {supabase,userId}=await requireModule("finance"); const id=String(fd.get("id")); const {data:row,error:readError}=await supabase.from("finance_transactions").select("payment_method").eq("id",id).eq("user_id",userId).maybeSingle(); if(readError)throw new Error(readError.message); if(row?.payment_method==="Belanja otomatis")throw new Error("Transaksi ini berasal dari menu Belanja. Hapus catatan belanjanya agar keduanya tetap sinkron."); const {error}=await supabase.from("finance_transactions").delete().eq("id",id).eq("user_id",userId); if(error) throw new Error(error.message); refresh(); }
export async function saveBudget(fd:FormData){ const {supabase,userId}=await requireModule("finance"); const month=`${String(fd.get("month"))}-01`; const category=String(fd.get("category")||"Total").trim()||"Total"; const {error}=await supabase.from("finance_budgets").upsert({user_id:userId,month,category,amount:positive(fd.get("amount"))},{onConflict:"user_id,month,category"}); if(error) throw new Error(error.message); refresh(); redirect("/finance?success=budget"); }
export async function addRecurring(fd:FormData){ const {supabase,userId}=await requireModule("finance"); const {error}=await supabase.from("finance_recurring").insert({user_id:userId,kind:String(fd.get("kind")),title:String(fd.get("title")||"").trim(),category:String(fd.get("category")||"Lainnya").trim(),amount:positive(fd.get("amount")),day_of_month:Number(fd.get("day_of_month")||1),active:true}); if(error) throw new Error(error.message); refresh(); redirect("/finance?success=recurring"); }
export async function postRecurringNow(fd:FormData){ const {supabase,userId}=await requireModule("finance"); const id=String(fd.get("id")); const {data:r,error:e1}=await supabase.from("finance_recurring").select("kind,title,category,amount").eq("id",id).eq("user_id",userId).single(); if(e1||!r) throw new Error(e1?.message||"Data tidak ditemukan"); const {error}=await supabase.from("finance_transactions").insert({user_id:userId,kind:r.kind,amount:r.amount,category:r.category,description:r.title,transaction_date:new Date().toISOString().slice(0,10),payment_method:"Rutin"}); if(error) throw new Error(error.message); refresh(); }
export async function toggleRecurring(fd:FormData){ const {supabase,userId}=await requireModule("finance"); const active=String(fd.get("active"))==="true"; const {error}=await supabase.from("finance_recurring").update({active:!active}).eq("id",String(fd.get("id"))).eq("user_id",userId); if(error) throw new Error(error.message); refresh(); }
