import { Factory } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { ModuleSubnav } from "@/components/module-subnav";
import { SectionCard } from "@/components/section-card";
import { StatCard } from "@/components/stat-card";
import { SubmitButton } from "@/components/submit-button";
import { EmptyState } from "@/components/empty-state";
import { requireModule } from "@/lib/auth";
import { readableDate, today } from "@/lib/format";
import { kebabNav } from "@/features/kebab/nav";
import { recordProduction } from "@/features/kebab/actions";

export default async function ProductionPage({searchParams}:{searchParams:Promise<{success?:string}>}){const {supabase}=await requireModule("kebab");const [recipesRes,prodRes]=await Promise.all([supabase.from("kebab_recipes").select("id,name").eq("active",true).order("name"),supabase.from("kebab_productions").select("id,quantity,production_date,notes,created_at,kebab_recipes(name)").order("production_date",{ascending:false}).order("created_at",{ascending:false}).limit(80)]);const recipes=recipesRes.data??[];const productions=prodRes.data??[];const todayQty=productions.filter((x:any)=>x.production_date===today()).reduce((s:number,x:any)=>s+Number(x.quantity),0);const params=await searchParams;return <><PageHeader eyebrow="Operasional Finka" title="Produksi Harian" description="Finka cukup memilih produk dan jumlah yang dibuat. Sistem mengurangi stok berdasarkan resep secara atomik; produksi ditolak bila bahan tidak cukup."/><ModuleSubnav items={kebabNav}/>{params.success&&<div className="rounded-xl bg-emerald-50 px-4 py-3 text-sm text-emerald-700">Produksi berhasil dicatat dan stok resep sudah dikurangi.</div>}<div className="grid gap-4 md:grid-cols-2"><StatCard label="Produksi hari ini" value={`${todayQty} pcs`} icon={Factory}/><StatCard label="Resep aktif" value={String(recipes.length)} icon={Factory}/></div><div className="grid gap-6 xl:grid-cols-[.7fr_1.3fr]"><SectionCard title="Catat produksi"><form action={recordProduction} className="space-y-3"><select className="field" name="recipe_id" required><option value="">Pilih produk</option>{recipes.map((r:any)=><option key={r.id} value={r.id}>{r.name}</option>)}</select><input className="field" name="quantity" type="number" min="1" step="1" placeholder="Jumlah dibuat" required/><input className="field" name="production_date" type="date" defaultValue={today()} required/><textarea className="field min-h-24" name="notes" placeholder="Catatan produksi"/><SubmitButton>Catat produksi</SubmitButton></form></SectionCard><SectionCard title="Riwayat produksi">{productions.length===0?<EmptyState/>:<div className="table-wrap"><table className="table"><thead><tr><th>Tanggal</th><th>Produk</th><th>Jumlah</th><th>Catatan</th></tr></thead><tbody>{productions.map((p:any)=><tr key={p.id}><td>{readableDate(p.production_date)}</td><td className="font-bold">{p.kebab_recipes?.name||"-"}</td><td className="font-black">{p.quantity} pcs</td><td>{p.notes||"-"}</td></tr>)}</tbody></table></div>}</SectionCard></div></>}
