import { createHmac, timingSafeEqual } from "crypto";
import { NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/admin";

export const runtime = "nodejs";

type AdminClient = ReturnType<typeof createAdminClient>;

function validSignature(rawBody:string, signature:string|null){const secret=process.env.META_APP_SECRET;if(!secret||!signature?.startsWith("sha256="))return false;const expected=createHmac("sha256",secret).update(rawBody).digest("hex");const received=signature.slice(7);if(expected.length!==received.length)return false;return timingSafeEqual(Buffer.from(expected),Buffer.from(received));}

export async function GET(request:Request){const url=new URL(request.url);const mode=url.searchParams.get("hub.mode");const token=url.searchParams.get("hub.verify_token");const challenge=url.searchParams.get("hub.challenge");if(mode==="subscribe"&&token===process.env.WHATSAPP_VERIFY_TOKEN&&challenge)return new Response(challenge,{status:200});return new Response("Forbidden",{status:403});}

export async function POST(request:Request){const raw=await request.text();if(!validSignature(raw,request.headers.get("x-hub-signature-256")))return new Response("Invalid signature",{status:401});let payload:any;try{payload=JSON.parse(raw)}catch{return new Response("Bad JSON",{status:400})}const messages=payload?.entry?.flatMap((e:any)=>e.changes??[]).flatMap((c:any)=>c.value?.messages??[])??[];if(!messages.length)return NextResponse.json({ok:true});const admin=createAdminClient();for(const msg of messages){const from=String(msg.from??"").replace(/[^0-9]/g,"");const text=String(msg.text?.body??"").trim();if(!from||!text)continue;const {data:profile}=await admin.from("profiles").select("id,display_name").eq("whatsapp_number",from).maybeSingle();if(!profile?.id){await sendWhatsAppText(from,"Nomor ini belum terhubung ke akun Personal Hub. Tambahkan nomor WhatsApp dari halaman Pengaturan.");continue;}const response=await executeCommand(admin,profile.id,text);await sendWhatsAppText(from,response)}return NextResponse.json({ok:true});}

async function hasModule(admin:AdminClient,userId:string,moduleKey:string){const {data}=await admin.from("user_modules").select("module_key").eq("user_id",userId).eq("module_key",moduleKey).eq("enabled",true).maybeSingle();return Boolean(data)}

async function executeCommand(admin:AdminClient,userId:string,text:string){const normalized=text.trim();const lower=normalized.toLowerCase();if(["help","bantuan","menu"].includes(lower))return helpText();

 const money=lower.match(/^(pengeluaran|pemasukan|belanja)\s+([0-9.,]+\s*(?:rb|ribu|jt|juta)?)\s+(.+)$/i);if(money){const type=money[1];const amount=parseMoney(money[2]);const description=normalized.slice(normalized.toLowerCase().indexOf(money[3]));if(!Number.isFinite(amount)||amount<=0)return "Nominal belum terbaca. Contoh: pengeluaran 50rb bensin";const date=new Date().toISOString().slice(0,10);if(type==="belanja"){if(!await hasModule(admin,userId,"shopping"))return "Modul Belanja tidak aktif di akun ini.";const {error}=await admin.from("shopping_entries").insert({user_id:userId,item_name:description,category:"WhatsApp",quantity:1,unit:"item",total_amount:amount,purchased_at:date,notes:"Dicatat via WhatsApp"});if(error)return `Gagal mencatat: ${error.message}`;return `✅ Belanja ${rupiahPlain(amount)} — ${description} berhasil dicatat.`}if(!await hasModule(admin,userId,"finance"))return "Modul Keuangan tidak aktif di akun ini.";const {error}=await admin.from("finance_transactions").insert({user_id:userId,kind:type==="pemasukan"?"income":"expense",amount,category:"WhatsApp",description,payment_method:"WhatsApp",transaction_date:date});if(error)return `Gagal mencatat: ${error.message}`;return `✅ ${type==="pemasukan"?"Pemasukan":"Pengeluaran"} ${rupiahPlain(amount)} — ${description} berhasil dicatat.`}

 if(lower.startsWith("tugas minggu")){if(!await hasModule(admin,userId,"academic"))return "Modul Kuliah tidak aktif di akun ini.";const now=new Date();const end=new Date(now.getTime()+7*86400000);const {data}=await admin.from("academic_assignments").select("title,due_date").eq("user_id",userId).eq("is_done",false).gte("due_date",now.toISOString().slice(0,10)).lte("due_date",end.toISOString().slice(0,10)).order("due_date");if(!data?.length)return "📚 Tidak ada deadline dalam 7 hari ke depan.";return "📚 Deadline 7 hari:\n"+data.map((x:any)=>`• ${x.due_date} — ${x.title}`).join("\n")}

 const task=normalized.match(/^tugas\s+(.+?)\s*\|\s*(\d{4}-\d{2}-\d{2})$/i);if(task){if(!await hasModule(admin,userId,"academic"))return "Modul Kuliah tidak aktif di akun ini.";const {error}=await admin.from("academic_assignments").insert({user_id:userId,title:task[1].trim(),due_date:task[2],priority:"normal",progress:0,is_done:false,description:"Dicatat via WhatsApp"});if(error)return `Gagal mencatat tugas: ${error.message}`;return `✅ Tugas “${task[1].trim()}” dicatat. Deadline ${task[2]}.`}

 const stock=normalized.match(/^stok\s+(.+)$/i);if(stock){if(!await hasModule(admin,userId,"kebab"))return "Modul Operasional Finka tidak aktif di akun ini.";const {data}=await admin.from("kebab_ingredients").select("name,unit,stock_quantity,low_stock_threshold").eq("user_id",userId).ilike("name",`%${stock[1].trim()}%`).limit(5);if(!data?.length)return "Bahan tidak ditemukan.";return "📦 Stok:\n"+data.map((x:any)=>`• ${x.name}: ${x.stock_quantity} ${x.unit}${Number(x.stock_quantity)<=Number(x.low_stock_threshold)?" ⚠️":""}`).join("\n")}

 const production=normalized.match(/^produksi\s+(.+?)\s+(\d+)$/i);if(production){if(!await hasModule(admin,userId,"kebab"))return "Modul Operasional Finka tidak aktif di akun ini.";const name=production[1].trim();const qty=Number(production[2]);const {data:recipe}=await admin.from("kebab_recipes").select("id,name").eq("user_id",userId).ilike("name",name).eq("active",true).limit(1).maybeSingle();if(!recipe)return `Resep “${name}” tidak ditemukan.`;const {error}=await admin.rpc("admin_record_kebab_production",{p_user_id:userId,p_recipe_id:recipe.id,p_quantity:qty,p_production_date:new Date().toISOString().slice(0,10),p_notes:"Dicatat via WhatsApp"});if(error)return `Produksi gagal: ${error.message}`;return `✅ Produksi ${qty} ${recipe.name} berhasil dicatat dan stok bahan sudah dikurangi.`}

 return "Perintah belum dikenali. Ketik *bantuan* untuk melihat contoh.";}

function parseMoney(raw:string){const value=raw.toLowerCase().replace(/\s+/g,"");const multiplier=value.endsWith("juta")||value.endsWith("jt")?1_000_000:value.endsWith("ribu")||value.endsWith("rb")?1_000:1;const numeric=value.replace(/(juta|ribu|jt|rb)$/i,"");const normalized=multiplier>1?numeric.replace(",","."):numeric.replace(/[.,]/g,"");return Number(normalized)*multiplier;}
function rupiahPlain(n:number){return new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n)}
function helpText(){return `Perintah Personal Hub:\n• pengeluaran 50rb bensin\n• pemasukan 250rb freelance\n• belanja 75rb beras\n• tugas Laporan Basis Data | 2026-09-20\n• tugas minggu ini\n• stok tortilla\n• produksi Kebab Original 50\n\nWebsite tetap menjadi pusat utama untuk edit/detail data.`}

async function sendWhatsAppText(to:string,body:string){const token=process.env.WHATSAPP_ACCESS_TOKEN;const phoneId=process.env.WHATSAPP_PHONE_NUMBER_ID;if(!token||!phoneId)return;const version=process.env.META_GRAPH_API_VERSION||"v23.0";await fetch(`https://graph.facebook.com/${version}/${phoneId}/messages`,{method:"POST",headers:{Authorization:`Bearer ${token}`,"Content-Type":"application/json"},body:JSON.stringify({messaging_product:"whatsapp",to,type:"text",text:{body}})}).catch(()=>undefined)}
