import { AlertTriangle, Bell, CheckCheck, Clock3 } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { SectionCard } from "@/components/section-card";
import { EmptyState } from "@/components/empty-state";
import { getProfileAndModules } from "@/lib/auth";
import { monthRange, readableDate, readableDateTime, rupiah, today } from "@/lib/format";
import { markAllNotificationsRead, markNotificationRead } from "@/features/notifications/actions";

export default async function NotificationsPage(){const {supabase,modules}=await getProfileAndModules();const {start,end}=monthRange();const [{data:stored},{data:assignments},{data:tx},{data:budgets}]=await Promise.all([supabase.from("notifications").select("id,title,message,kind,is_read,created_at").order("created_at",{ascending:false}).limit(80),modules.includes("academic")?supabase.from("academic_assignments").select("id,title,due_date").eq("is_done",false).gte("due_date",today()).order("due_date").limit(10):Promise.resolve({data:[] as any[]}),modules.includes("finance")?supabase.from("finance_transactions").select("kind,amount").gte("transaction_date",start).lt("transaction_date",end):Promise.resolve({data:[] as any[]}),modules.includes("finance")?supabase.from("finance_budgets").select("category,amount").eq("month",start):Promise.resolve({data:[] as any[]})]);let ingredients:any[]=[];if(modules.includes("kebab")){const r=await supabase.from("kebab_ingredients").select("id,name,unit,stock_quantity,low_stock_threshold,expires_at").order("name");ingredients=r.data??[];}const expense=(tx??[]).filter((x:any)=>x.kind==="expense").reduce((s:number,x:any)=>s+Number(x.amount),0);const budgetRows=budgets??[];const budget=Number(budgetRows.find((x:any)=>x.category==="Total")?.amount??budgetRows.reduce((s:number,x:any)=>s+Number(x.amount),0));const low=ingredients.filter((x:any)=>Number(x.stock_quantity)<=Number(x.low_stock_threshold));const soon=ingredients.filter((x:any)=>x.expires_at&&new Date(`${x.expires_at}T23:59:59`)<=new Date(Date.now()+7*86400000));const unread=(stored??[]).filter((x:any)=>!x.is_read).length;
return <><PageHeader eyebrow="Pusat perhatian" title="Notifikasi" description="Gabungan notifikasi tersimpan dan peringatan langsung dari kondisi data." action={unread>0?<form action={markAllNotificationsRead}><button className="btn-soft"><CheckCheck size={16}/> Tandai semua dibaca</button></form>:undefined}/><div className="grid gap-6 xl:grid-cols-2"><SectionCard title="Peringatan langsung" description="Dihitung dari data terbaru setiap halaman dibuka."><div className="space-y-2">{budget>0&&expense/budget>=.8&&<Notice icon={<AlertTriangle/>} title="Budget bulan ini hampir habis" text={`${Math.round(expense/budget*100)}% terpakai · ${rupiah(expense)} dari ${rupiah(budget)}`}/>} {(assignments??[]).map((a:any)=><Notice key={a.id} icon={<Clock3/>} title={`Deadline: ${a.title}`} text={readableDate(a.due_date)}/>) }{low.map((i:any)=><Notice key={`low-${i.id}`} icon={<AlertTriangle/>} title={`Stok ${i.name} hampir habis`} text={`Sisa ${i.stock_quantity} ${i.unit}`}/>) }{soon.map((i:any)=><Notice key={`exp-${i.id}`} icon={<AlertTriangle/>} title={`${i.name} mendekati expired`} text={readableDate(i.expires_at)}/>) }{!(budget>0&&expense/budget>=.8)&&(assignments??[]).length===0&&low.length===0&&soon.length===0&&<EmptyState>Tidak ada peringatan langsung.</EmptyState>}</div></SectionCard><SectionCard title="Riwayat notifikasi" description="Notifikasi yang dibuat otomatis oleh proses tertentu.">{(stored??[]).length===0?<EmptyState/>:<div className="space-y-2">{(stored??[]).map((n:any)=><div key={n.id} className={`rounded-xl border border-black/5 p-4 ${n.is_read?"bg-neutral-50 opacity-70":"bg-white"}`}><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><Bell size={17} className="mt-0.5 text-orange-600"/><div><p className="font-black">{n.title}</p><p className="mt-1 text-sm text-neutral-500">{n.message}</p><p className="mt-2 text-xs text-neutral-400">{readableDateTime(n.created_at)}</p></div></div>{!n.is_read&&<form action={markNotificationRead}><input type="hidden" name="id" value={n.id}/><button className="btn-soft">Dibaca</button></form>}</div></div>)}</div>}</SectionCard></div></>}
function Notice({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="flex gap-3 rounded-xl bg-amber-50 p-3 text-amber-900"><div className="mt-0.5 [&>svg]:h-4 [&>svg]:w-4">{icon}</div><div><p className="text-sm font-black">{title}</p><p className="mt-1 text-xs opacity-80">{text}</p></div></div>}
