import { CalendarClock } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { ModuleSubnav } from "@/components/module-subnav";
import { SectionCard } from "@/components/section-card";
import { SubmitButton } from "@/components/submit-button";
import { EmptyState } from "@/components/empty-state";
import { academicNav } from "@/features/academic/nav";
import { addEvent } from "@/features/academic/actions";
import { requireModule } from "@/lib/auth";
import { readableDateTime } from "@/lib/format";

export default async function CalendarPage(){const {supabase}=await requireModule("academic");const [coursesRes,eventsRes]=await Promise.all([supabase.from("academic_courses").select("id,name").order("name"),supabase.from("academic_events").select("id,title,event_type,starts_at,ends_at,location,notes,academic_courses(name)").order("starts_at").limit(120)]);const courses=coursesRes.data??[];const events=eventsRes.data??[];return <><PageHeader eyebrow="Kuliah" title="Kalender Akademik" description="UTS, UAS, presentasi, praktikum, deadline administratif, dan agenda akademik lain."/><ModuleSubnav items={academicNav}/><div className="grid gap-6 xl:grid-cols-[.7fr_1.3fr]"><SectionCard title="Tambah agenda"><form action={addEvent} className="space-y-3"><select className="field" name="course_id"><option value="">Umum</option>{courses.map((c:any)=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input className="field" name="title" placeholder="Nama agenda" required/><select className="field" name="event_type"><option value="exam">Ujian</option><option value="presentation">Presentasi</option><option value="practicum">Praktikum</option><option value="deadline">Deadline</option><option value="other">Lainnya</option></select><label className="label">Mulai</label><input className="field" name="starts_at" type="datetime-local" required/><label className="label">Selesai (opsional)</label><input className="field" name="ends_at" type="datetime-local"/><input className="field" name="location" placeholder="Lokasi / ruang"/><textarea className="field min-h-20" name="notes" placeholder="Catatan"/><SubmitButton>Tambah agenda</SubmitButton></form></SectionCard><SectionCard title="Agenda">{events.length===0?<EmptyState/>:<div className="space-y-2">{events.map((e:any)=><div key={e.id} className="flex gap-3 rounded-xl border border-black/5 p-4"><div className="rounded-xl bg-orange-50 p-2 text-orange-600"><CalendarClock size={18}/></div><div><div className="flex flex-wrap items-center gap-2"><p className="font-black">{e.title}</p><span className="pill">{e.event_type}</span></div><p className="mt-1 text-xs text-neutral-500">{readableDateTime(e.starts_at)} · {e.academic_courses?.name||"Umum"}</p><p className="mt-1 text-sm text-neutral-600">{e.location||"Tanpa lokasi"}{e.notes?` · ${e.notes}`:""}</p></div></div>)}</div>}</SectionCard></div></>}
