"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireModule } from "@/lib/auth";
function positive(v:unknown){const n=Number(v);if(!Number.isFinite(n)||n<=0)throw new Error("Jumlah harus lebih dari 0.");return n;}
function nonnegative(v:unknown){const n=Number(v);if(!Number.isFinite(n)||n<0)throw new Error("Nilai tidak valid.");return n;}
function refresh(){revalidatePath("/kebab");revalidatePath("/kebab/ingredients");revalidatePath("/kebab/recipes");revalidatePath("/kebab/production");revalidatePath("/kebab/purchases");revalidatePath("/kebab/stock");revalidatePath("/dashboard");revalidatePath("/reports");revalidatePath("/notifications");}
export async function addIngredient(fd:FormData){const {supabase,userId}=await requireModule("kebab");const {error}=await supabase.from("kebab_ingredients").insert({user_id:userId,name:String(fd.get("name")||"").trim(),unit:String(fd.get("unit")||"").trim(),stock_quantity:nonnegative(fd.get("initial_stock")||0),low_stock_threshold:nonnegative(fd.get("low_stock_threshold")||0),last_unit_cost:nonnegative(fd.get("last_unit_cost")||0),expires_at:String(fd.get("expires_at")||"")||null});if(error)throw new Error(error.message);refresh();redirect("/kebab/ingredients?success=ingredient");}
export async function addSupplier(fd:FormData){const {supabase,userId}=await requireModule("kebab");const {error}=await supabase.from("kebab_suppliers").insert({user_id:userId,name:String(fd.get("name")||"").trim(),phone:String(fd.get("phone")||"").trim(),notes:String(fd.get("notes")||"").trim()});if(error)throw new Error(error.message);refresh();redirect("/kebab/purchases?success=supplier");}
export async function recordPurchase(fd:FormData){const {supabase}=await requireModule("kebab");const {error}=await supabase.rpc("record_kebab_purchase",{p_ingredient_id:String(fd.get("ingredient_id")),p_supplier_id:String(fd.get("supplier_id")||"")||null,p_quantity:positive(fd.get("quantity")),p_total_cost:positive(fd.get("total_cost")),p_purchased_at:String(fd.get("purchased_at")),p_expires_at:String(fd.get("expires_at")||"")||null,p_note:String(fd.get("note")||"").trim()});if(error)throw new Error(error.message);refresh();redirect("/kebab/purchases?success=purchase");}
export async function recordStockMovement(fd:FormData){const {supabase}=await requireModule("kebab");const {error}=await supabase.rpc("record_kebab_stock_movement",{p_ingredient_id:String(fd.get("ingredient_id")),p_direction:String(fd.get("direction")),p_quantity:positive(fd.get("quantity")),p_unit_cost:nonnegative(fd.get("unit_cost")||0),p_note:String(fd.get("note")||"").trim()});if(error)throw new Error(error.message);refresh();redirect("/kebab/ingredients?success=movement");}
export async function addRecipe(fd:FormData){const {supabase,userId}=await requireModule("kebab");const {error}=await supabase.from("kebab_recipes").insert({user_id:userId,name:String(fd.get("name")||"").trim(),selling_price:nonnegative(fd.get("selling_price")||0),active:true});if(error)throw new Error(error.message);refresh();redirect("/kebab/recipes?success=recipe");}
export async function addRecipeItem(fd:FormData){const {supabase,userId}=await requireModule("kebab");const {error}=await supabase.from("kebab_recipe_items").upsert({user_id:userId,recipe_id:String(fd.get("recipe_id")),ingredient_id:String(fd.get("ingredient_id")),quantity_per_unit:positive(fd.get("quantity_per_unit"))},{onConflict:"recipe_id,ingredient_id"});if(error)throw new Error(error.message);refresh();redirect("/kebab/recipes?success=item");}
export async function recordProduction(fd:FormData){const {supabase}=await requireModule("kebab");const {error}=await supabase.rpc("record_kebab_production",{p_recipe_id:String(fd.get("recipe_id")),p_quantity:Math.floor(positive(fd.get("quantity"))),p_production_date:String(fd.get("production_date")),p_notes:String(fd.get("notes")||"").trim()});if(error)throw new Error(error.message);refresh();redirect("/kebab/production?success=production");}
export async function recordWaste(fd:FormData){const {supabase}=await requireModule("kebab");const {error}=await supabase.rpc("record_kebab_waste",{p_ingredient_id:String(fd.get("ingredient_id")),p_quantity:positive(fd.get("quantity")),p_reason:String(fd.get("reason")||"").trim(),p_waste_date:String(fd.get("waste_date"))});if(error)throw new Error(error.message);refresh();redirect("/kebab/stock?success=waste");}
export async function performStockOpname(fd:FormData){const {supabase}=await requireModule("kebab");const {error}=await supabase.rpc("perform_kebab_stock_opname",{p_ingredient_id:String(fd.get("ingredient_id")),p_actual_quantity:nonnegative(fd.get("actual_quantity")),p_note:String(fd.get("note")||"").trim()});if(error)throw new Error(error.message);refresh();redirect("/kebab/stock?success=opname");}
