"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireModule } from "@/lib/auth";

function refresh(){revalidatePath("/academic");revalidatePath("/academic/materials");revalidatePath("/academic/study");revalidatePath("/academic/grades");revalidatePath("/academic/calendar");revalidatePath("/dashboard");revalidatePath("/reports");}
function n(v:FormDataEntryValue|null,fallback=0){const x=Number(v);return Number.isFinite(x)?x:fallback;}

export async function addCourse(fd:FormData){const {supabase,userId}=await requireModule("academic");const {error}=await supabase.from("academic_courses").insert({user_id:userId,code:String(fd.get("code")||"").trim(),name:String(fd.get("name")||"").trim(),lecturer:String(fd.get("lecturer")||"").trim(),semester:String(fd.get("semester")||"").trim(),credits:n(fd.get("credits"),0)});if(error)throw new Error(error.message);refresh();redirect("/academic?success=course");}
export async function addAssignment(fd:FormData){const {supabase,userId}=await requireModule("academic");const {error}=await supabase.from("academic_assignments").insert({user_id:userId,course_id:String(fd.get("course_id")||"")||null,title:String(fd.get("title")||"").trim(),description:String(fd.get("description")||"").trim(),due_date:String(fd.get("due_date")),priority:String(fd.get("priority")||"normal"),progress:n(fd.get("progress"),0),is_done:false});if(error)throw new Error(error.message);refresh();redirect("/academic?success=assignment");}
export async function toggleAssignment(fd:FormData){const {supabase,userId}=await requireModule("academic");const done=String(fd.get("done"))==="true";const {error}=await supabase.from("academic_assignments").update({is_done:!done,progress:!done?100:n(fd.get("progress"),0)}).eq("id",String(fd.get("id"))).eq("user_id",userId);if(error)throw new Error(error.message);refresh();}
export async function setAssignmentProgress(fd:FormData){const {supabase,userId}=await requireModule("academic");const progress=Math.max(0,Math.min(100,n(fd.get("progress"),0)));const {error}=await supabase.from("academic_assignments").update({progress,is_done:progress===100}).eq("id",String(fd.get("id"))).eq("user_id",userId);if(error)throw new Error(error.message);refresh();revalidatePath(`/academic/assignments/${String(fd.get("id"))}`);}
export async function addAssignmentStep(fd:FormData){const {supabase,userId}=await requireModule("academic");const assignmentId=String(fd.get("assignment_id"));const {error}=await supabase.from("academic_assignment_steps").insert({user_id:userId,assignment_id:assignmentId,title:String(fd.get("title")||"").trim(),position:n(fd.get("position"),0)});if(error)throw new Error(error.message);refresh();revalidatePath(`/academic/assignments/${assignmentId}`);}
export async function toggleAssignmentStep(fd:FormData){const {supabase,userId}=await requireModule("academic");const id=String(fd.get("id"));const assignmentId=String(fd.get("assignment_id"));const done=String(fd.get("done"))==="true";const {error}=await supabase.from("academic_assignment_steps").update({is_done:!done}).eq("id",id).eq("user_id",userId);if(error)throw new Error(error.message);revalidatePath(`/academic/assignments/${assignmentId}`);}
export async function addSchedule(fd:FormData){const {supabase,userId}=await requireModule("academic");const {error}=await supabase.from("academic_schedules").insert({user_id:userId,course_id:String(fd.get("course_id")||"")||null,weekday:n(fd.get("weekday")),start_time:String(fd.get("start_time")),end_time:String(fd.get("end_time")),room:String(fd.get("room")||"").trim(),meeting_url:String(fd.get("meeting_url")||"").trim()});if(error)throw new Error(error.message);refresh();redirect("/academic?success=schedule");}
export async function addNote(fd:FormData){const {supabase,userId}=await requireModule("academic");const {error}=await supabase.from("academic_notes").insert({user_id:userId,course_id:String(fd.get("course_id")||"")||null,title:String(fd.get("title")||"").trim(),content:String(fd.get("content")||"").trim(),meeting_no:n(fd.get("meeting_no"),0),resource_url:String(fd.get("resource_url")||"").trim()});if(error)throw new Error(error.message);refresh();redirect("/academic/materials?success=note");}
export async function uploadMaterial(fd:FormData){const {supabase,userId}=await requireModule("academic");const file=fd.get("file");if(!(file instanceof File)||file.size===0)throw new Error("Pilih file terlebih dahulu.");if(file.size>10*1024*1024)throw new Error("Maksimal file 10 MB.");const courseId=String(fd.get("course_id")||"")||null;const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"-");const path=`${userId}/${courseId||"general"}/${crypto.randomUUID()}-${safe}`;const {error:uploadError}=await supabase.storage.from("academic-materials").upload(path,file,{upsert:false});if(uploadError)throw new Error(uploadError.message);const {error}=await supabase.from("academic_materials").insert({user_id:userId,course_id:courseId,title:String(fd.get("title")||file.name).trim(),storage_path:path,file_name:file.name,file_size:file.size,mime_type:file.type||"application/octet-stream"});if(error){await supabase.storage.from("academic-materials").remove([path]);throw new Error(error.message);}refresh();redirect("/academic/materials?success=file");}
export async function addStudySession(fd:FormData){const {supabase,userId}=await requireModule("academic");const duration=Math.max(1,Math.floor(n(fd.get("duration_minutes"),25)));const {error}=await supabase.from("academic_study_sessions").insert({user_id:userId,course_id:String(fd.get("course_id")||"")||null,title:String(fd.get("title")||"Study session").trim(),duration_minutes:duration,notes:String(fd.get("notes")||"").trim(),completed_at:new Date().toISOString()});if(error)throw new Error(error.message);refresh();redirect("/academic/study?success=session");}
export async function addGrade(fd:FormData){const {supabase,userId}=await requireModule("academic");const {error}=await supabase.from("academic_grades").insert({user_id:userId,course_id:String(fd.get("course_id")),label:String(fd.get("label")||"").trim(),score:n(fd.get("score")),max_score:n(fd.get("max_score"),100),weight:n(fd.get("weight"),0)});if(error)throw new Error(error.message);refresh();redirect("/academic/grades?success=grade");}
export async function saveTarget(fd:FormData){const {supabase,userId}=await requireModule("academic");const semester=String(fd.get("semester")||"").trim();const {error}=await supabase.from("academic_targets").upsert({user_id:userId,semester,target_gpa:n(fd.get("target_gpa"),0),notes:String(fd.get("notes")||"").trim()},{onConflict:"user_id,semester"});if(error)throw new Error(error.message);refresh();redirect("/academic/grades?success=target");}
export async function addEvent(fd:FormData){const {supabase,userId}=await requireModule("academic");const {error}=await supabase.from("academic_events").insert({user_id:userId,course_id:String(fd.get("course_id")||"")||null,title:String(fd.get("title")||"").trim(),event_type:String(fd.get("event_type")||"other"),starts_at:String(fd.get("starts_at")),ends_at:String(fd.get("ends_at")||"")||null,location:String(fd.get("location")||"").trim(),notes:String(fd.get("notes")||"").trim()});if(error)throw new Error(error.message);refresh();redirect("/academic/calendar?success=event");}

export async function deleteMaterial(fd:FormData){const {supabase,userId}=await requireModule("academic");const id=String(fd.get("id"));const {data:row}=await supabase.from("academic_materials").select("storage_path").eq("id",id).eq("user_id",userId).maybeSingle();if(!row)throw new Error("Materi tidak ditemukan.");const {error}=await supabase.from("academic_materials").delete().eq("id",id).eq("user_id",userId);if(error)throw new Error(error.message);await supabase.storage.from("academic-materials").remove([row.storage_path]);refresh();}
